name: Python CI
run-name: ${{ github.actor }} Check if the latest commit is breaking anything
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential gcc
    - name: Install packages
      run: make install
    - name: Format
      run: make format
    - name: Lint
      run: make lint
    - name: Test
      run: make test
