name: Python CI
run-name: ${{ github.actor }} Check if the latest commit is breaking anything
on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Say hello
      run: echo "Hello from GitHub Actions!"
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential gcc
